version: "3.8"
services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - 3307:3306
    volumes:
      - ./dbgamedev:/var/lib/mysql
  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    restart: unless-stopped
    ports:
      - 6380:6379
    volumes:
      - redisdata:/data
volumes:
  redisdata:
  db:
